apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend:latest
        ports:
        - containerPort: 3000 # assuming my frontend runs on port 3000
        env:
        - name: BACKEND_URL
          value: "http://backend-service:5000" # Environment variable to access backend
