apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: sepel24/frontend:latest
        ports:
        - containerPort: 8080 
        env:
        - name: BACKEND_PORT
          value: "9000"
        - name: BACKEND_DNS
          value: backend