name: Pipeline

# Esegui il workflow su push o pull request verso il branch main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.12'
      - name: Run application
        run:  |
            cd backend
            go build -buildvcs=false
            cd ../frontend
            go build -buildvcs=false
      - name: Test application
        run: |
            cd frontend
            go test


