name: Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull the repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.14'
      - name: Build Backend
        run:  |
            cd backend
            go build -buildvcs=false
      - name: Build Frontend
        run:  |
            cd frontend
            go build -buildvcs=false
      - name: Test application
        run: |
            cd frontend
            go test


